# Generated by Django 5.2.7 on 2025-11-07 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAPIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=200, verbose_name='店舗名')),
                ('api_url', models.URLField(verbose_name='APIエンドポイントURL')),
                ('api_key', models.CharField(max_length=500, verbose_name='APIキー')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sample_data', models.JSONField(blank=True, help_text='外部APIから取得したサンプルデータ', null=True, verbose_name='サンプルデータ')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '外部API設定',
                'verbose_name_plural': '外部API設定',
            },
        ),
        migrations.CreateModel(
            name='ProductImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '処理中'), ('success', '成功'), ('partial', '一部成功'), ('failed', '失敗')], default='pending', max_length=20, verbose_name='ステータス')),
                ('total_count', models.IntegerField(default=0, verbose_name='総件数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功件数')),
                ('failed_count', models.IntegerField(default=0, verbose_name='失敗件数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.externalapiconfig', verbose_name='API設定')),
            ],
            options={
                'verbose_name': 'インポートログ',
                'verbose_name_plural': 'インポートログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_column', models.CharField(choices=[('product_name', '商品名'), ('ingredients_list', '成分表'), ('price', '価格'), ('image_url', '画像URL')], max_length=100, verbose_name='内部カラム名')),
                ('external_column', models.CharField(help_text='外部APIのレスポンスに含まれるカラム名', max_length=200, verbose_name='外部カラム名')),
                ('json_path', models.CharField(blank=True, help_text='ネストされたデータの場合のパス(例: data.items.0.name)', max_length=500, null=True, verbose_name='JSONパス')),
                ('transformation_rule', models.CharField(blank=True, choices=[('none', '変換なし'), ('to_int', '整数に変換'), ('to_float', '小数に変換'), ('strip_html', 'HTMLタグ除去'), ('join_array', '配列を結合')], default='none', max_length=50, null=True, verbose_name='変換ルール')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('api_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_mappings', to='api.externalapiconfig', verbose_name='API設定')),
            ],
            options={
                'verbose_name': 'カラムマッピング',
                'verbose_name_plural': 'カラムマッピング',
                'unique_together': {('api_config', 'internal_column')},
            },
        ),
    ]
