# Generated by Django 5.2.7 on 2025-10-21 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='Text',
            new_name='Contacts_text',
        ),
    ]
