# Generated by Django 5.2.7 on 2025-10-21 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_rename_text_contacts_contacts_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='Contacts_text',
            new_name='text',
        ),
    ]
