# Generated by Django 5.2.7 on 2025-10-21 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Skin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('INGREDIENTS_NAME', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('COMMENT', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='appropriate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appropriate', models.BooleanField(null=True)),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Skin.skin_type')),
                ('INGREDIENTS_NAME', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend.ingredients')),
            ],
        ),
    ]
