# Generated by Django 5.2.7 on 2025-11-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_lecture_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='ProductName',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.RemoveField(
            model_name='productname',
            name='lecture',
        ),
        migrations.AddField(
            model_name='productname',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='recommend.ingredients'),
        ),
    ]
