# Generated by Django 5.2.7 on 2025-10-31 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_access_product_id_remove_access_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Ingredients_list',
            new_name='ingredients_list',
        ),
    ]
