# Generated by Django 5.2.7 on 2025-11-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_ingredients_list_product_ingredients_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ingredients_list',
            field=models.TextField(blank=True, null=True, verbose_name='成分表'),
        ),
    ]
