# Generated by Django 5.2.7 on 2025-10-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skin_type',
            fields=[
                ('type_name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
    ]
